export const technologyIcons: Record<string, string> = {
  Python: "/tech/python.svg",
  FastAPI: "/tech/fastapi.svg",
  Celery: "/tech/celery.svg",
  Redis: "/tech/redis.svg",
  PostgreSQL: "/tech/postgresql.svg",
  Docker: "/tech/docker.svg",
  "Docker Compose": "/tech/docker.svg",
  React: "/tech/react.svg",
  TypeScript: "/tech/typescript.svg",
  JavaScript: "/tech/javascript.svg",
  "Node.js": "/tech/nodejs.svg",
  Express: "/tech/express.svg",
  "Socket.io": "/tech/socketio.svg",
  "Prisma ORM": "/tech/prisma.svg",
  Prisma: "/tech/prisma.svg",
  Vite: "/tech/vite.svg",
  Streamlit: "/tech/streamlit.svg",
  "C#": "/tech/csharp.svg",
  "C++17": "/tech/cplusplus.svg",
  "C++": "/tech/cplusplus.svg",
  ".NET 9": "/tech/dotnet.svg",
  ".NET": "/tech/dotnet.svg",
  Bootstrap: "/tech/bootstrap.svg",
  HTML: "/tech/html5.svg",
  HTML5: "/tech/html5.svg",
  CSS: "/tech/css3.svg",
  CSS3: "/tech/css3.svg",
  "Tailwind CSS": "/tech/tailwind.svg",
  SQLite: "/tech/sqlite.svg",
  MySQL: "/tech/mysql.svg",
  Pandas: "/tech/pandas.svg",
  Plotly: "/tech/plotly.svg",
  SQLAlchemy: "/tech/sqlalchemy.svg",
  Git: "/tech/git.svg",
  GitHub: "/tech/github.svg",
  "GitHub Actions": "/tech/githubactions.svg",
  Pytest: "/tech/pytest.svg",
  CMake: "/tech/cmake.svg",
  Java: "/tech/java.svg",
  PHP: "/tech/php.svg",
  Nginx: "/tech/nginx.svg",
  Render: "/tech/render.svg",
  Neon: "/tech/neon.svg",
  Resend: "/tech/resend.svg",
  JWT: "/tech/jwt.svg",
  Zod: "/tech/zod.svg",
  "React Router": "/tech/reactrouter.svg",
  "Lucide React": "/tech/lucide.svg",
  "TanStack Query": "/tech/tanstackquery.svg",
  Axios: "/tech/axios.svg",
  Ollama: "/tech/ollama.svg",
  "DeepL API": "/tech/deepl.svg",
  Django: "/tech/django.svg",
  PySide6: "/tech/qt.svg",
  Qt: "/tech/qt.svg",
  jQuery: "/tech/jquery.svg",
  WordPress: "/tech/wordpress.svg",
  Laravel: "/tech/laravel.svg",
  CodeIgniter: "/tech/codeigniter.svg",
  Sass: "/tech/sass.svg",
  Ionic: "/tech/ionic.svg",
  "Spring Boot": "/tech/springboot.svg",
  Hibernate: "/tech/hibernate.svg",
  MongoDB: "/tech/mongodb.svg",
  Firebase: "/tech/firebase.svg",
  CouchDB: "/tech/couchdb.svg",
  Godot: "/tech/godot.svg",
  GDScript: "/tech/gds.svg",
  Unity: "/tech/unity.svg",
  Selenium: "/tech/selenium.svg",
  Figma: "/tech/figma.svg",
  "Next.js": "/tech/nextjs.svg",
  PHPMyAdmin: "/tech/phpmyadmin.svg",
};

export function getTechnologyIcon(name: string) {
  return technologyIcons[name];
}
